services:
  frontend:
    build:
      context: ./frontend/FrontAngular/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/login-auth-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gerenc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9131
    ports:
      - "5432:5432"
